### ISSUE TITLE
Settings screen crash in 6.0 / Stratos

### ISSUE THREAD

**Issue by supertorpe** [micrusa/AmazTimer#19] opened 2020-07-02 07:03 UTC
The settings screen does not appear. This message is displayed: "Unfortunately, AmazTimer has stopped."
I have uninstalled previous version before 6.0 installation. Cleaning the application data doesn't fix it either.

**Comment by micrusa** [comment] 2020-07-02 07:33
I can't reproduce the bug, I installed it over a previous version and did adb shell pm clear me.micrusa.amaztimer and no crashes, can you send logs?

**Comment by 1immortal** [comment] 2020-07-02 10:38
please find attached:

07-02 13:37:50.662 412-424/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=me.micrusa.amaztimer cmp=me.micrusa.amaztimer/.AmazTimer} from uid 1000 on display 0
07-02 13:37:50.664 412-424/? V/WindowManager: addAppToken: AppWindowToken{e7379bb token=Token{2e8564a ActivityRecord{10d19fb5 u0 me.micrusa.amaztimer/.AmazTimer t1291}}} to stack=1 task=1291 at 0
07-02 13:37:50.814 412-639/? I/ActivityManager: Start proc 2447:me.micrusa.amaztimer/u0a28 for activity me.micrusa.amaztimer/.AmazTimer
07-02 13:37:54.222 412-525/? V/WindowManager: Adding window Window{91128ee u0 me.micrusa.amaztimer/me.micrusa.amaztimer.AmazTimer} at 2 of 4 (after Window{7f69f28 u0 com.huami.watch.launcher/com.huami.watch.launcher.Launcher})
07-02 13:37:54.528 85-129/? E/BufferQueueProducer: [me.micrusa.amaztimer/me.micrusa.amaztimer.AmazTimer] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
07-02 13:37:55.578 412-438/? I/ActivityManager: Displayed me.micrusa.amaztimer/.AmazTimer: +4s852ms
07-02 13:38:02.964 2447-2447/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.micrusa.amaztimer, PID: 2447
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.PowerManager$WakeLock.isHeld()' on a null object reference
        at c.a.a.r.d.c()
        at me.micrusa.amaztimer.AmazTimer.h(:1)
        at c.a.a.l.onLongClick(lambda)
        at android.view.View.performLongClick(View.java:4819)
        at android.widget.TextView.performLongClick(TextView.java:8684)
        at android.view.View$CheckForLongPress.run(View.java:19840)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-02 13:38:02.970 412-678/? W/ActivityManager:   Force finishing activity 1 me.micrusa.amaztimer/.AmazTimer
07-02 13:38:03.526 412-433/? W/ActivityManager: Activity pause timeout for ActivityRecord{10d19fb5 u0 me.micrusa.amaztimer/.AmazTimer t1291 f}
07-02 13:38:13.981 412-433/? W/ActivityManager: Activity destroy timeout for ActivityRecord{10d19fb5 u0 me.micrusa.amaztimer/.AmazTimer t1291 f}

**Comment by supertorpe** [comment] 2020-07-02 10:49
Process: me.micrusa.amaztimer
Flags: 0xe83e44
Package: me.micrusa.amaztimer v60 (6.0)
Build: Huami/everest-PACEfied27/watch:5.1/LMY47D/102:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.PowerManager$WakeLock.isHeld()' on a null object reference
	at c.a.a.r.d.c()
	at me.micrusa.amaztimer.AmazTimer.h(:1)
	at c.a.a.l.onLongClick(lambda)
	at android.view.View.performLongClick(View.java:4819)
	at android.widget.TextView.performLongClick(TextView.java:8684)
	at android.view.View$CheckForLongPress.run(View.java:19840)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by micrusa** [comment] 2020-07-02 11:32
Fixed in #20, I'll upload new release asap

**Closed as completed** 2020-07-02 11:33 UTC
