### ISSUE TITLE
Idea+problem

### ISSUE THREAD

**Issue by choniimillas** [micrusa/AmazTimer#23] opened 2020-07-17 20:53 UTC
Hi there, great work!
I downloaded and installed the apk yesterday in my Stratos 2. Used it to work outand pretty much worked out fine.
One thing I noticed is that the vibrtion level was quite low, It might be interesting to regulate the level, sometimes I didn't realize it vibrated. After using it for a couple of rounds it seemed that was running two rounds at the same time. And after finishing the one on screen the watch kept vibrating every 10 and 20 secs, and I couldn't close or finish anything sinche I could't find a round running.

I hope this comments work.

**Comment by micrusa** [comment] 2020-07-17 22:49
About the vibrations, I can't control intensity, just time so maybe I can add vibration times options, and about the other problem, I need more info, which mode were you using?

**Comment by micrusa** [comment] 2020-07-19 10:52
Added a preference to adjust vibrations on https://github.com/micrusa/AmazTimer/commit/986729b88ef7cff0676bbb2853765b92fb621d74

**Comment by choniimillas** [comment] 2020-07-20 13:43
Great,
I will keep on using it to understand when I have the problem I prevously mention.
I am new in github so I dont quite understand how it works. When you say you added the preference does it also udpates the apk file or is it something I should be doing so I can have it in my watch?

**Comment by 1immortal** [comment] 2020-07-20 13:47
you need to download the latest edgy again and install it over the current installation, or to remove the one installed and re-install again.

**Comment by micrusa** [comment] 2020-07-20 13:47
> Great,
> I will keep on using it to understand when I have the problem I prevously mention.
> I am new in github so I dont quite understand how it works. When you say you added the preference does it also udpates the apk file or is it something I should be doing so I can have it in my watch?

It updates the edgy build, but it might be unstable because I'm always doing changes, so if you want you can test it [here](https://github.com/micrusa/AmazTimer/releases/edgy) or wait for the stable release

**Comment by choniimillas** [comment] 2020-07-20 13:50
Great, thanks! @micrusa @1immortal

**Comment by micrusa** [comment] 2020-08-02 19:24
Any update? Should I close?

**Comment by choniimillas** [comment] 2020-08-04 22:42
I tried the new version and I keep having the other trouble I mentioned. It goes like this:
I set any number of sets and with the duration pretended.
The system runs properly, with or without the preparing time.
I finish the round and the start page appears again.
After some seconds, I guess the same amount that I used as the previous work time the watch vibrates and it starts the round infinetely. 
It doesnt show a current Work/rest  Cancel/finish Layout, it just vibrates.
It only stops if I restart the watch
If I start a new program the two vibrations overlay so the watch vibrates a lot.


I dont touch anything when I finish the first intended round.

I hope I made myself clear. I turned off every configuration and It doesnt help.

**Comment by micrusa** [comment] 2020-08-07 10:43
> I tried the new version and I keep having the other trouble I mentioned. It goes like this:
> I set any number of sets and with the duration pretended.
> The system runs properly, with or without the preparing time.
> I finish the round and the start page appears again.
> After some seconds, I guess the same amount that I used as the previous work time the watch vibrates and it starts the round infinetely. 
> It doesnt show a current Work/rest  Cancel/finish Layout, it just vibrates.
> It only stops if I restart the watch
> If I start a new program the two vibrations overlay so the watch vibrates a lot.
> 
> 
> I dont touch anything when I finish the first intended round.
> 
> I hope I made myself clear. I turned off every configuration and It doesnt help.

I can't reproduce the problem but I'll take a deeper look in the code for possible fixes. It seems that the workout haven't stopped and then another one started

**Comment by micrusa** [comment] 2020-08-22 19:15
Got fixed on 7.2

**Closed as completed by micrusa** 2020-08-22 19:15 UTC
